# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# site
title: HandshakeAcademy
author: urkel
language: en
lang: en
timezone: America/Boise

# url
url: https://www.handshakeacademy.org
root: /
permalink: :lang/:year/:month/:day/:title
# permalink_defaults:


deploy:
  type: git
  repo: git@github.com:HandshakeAlliance/handshakeacademy.org.git
  branch: gh-pages


# directory
source_dir: source
public_dir: public
tag_dir: tags

# archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# skip_render:
# include:
# exclude:

# writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false
external_link: true
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  # tab_replace:

# category
default_category: uncategorized
# category_map:
# tag_map:

# date & time format
date_format: MMMM D, YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
# theme
theme: handshake-academy

# hexo-generator-category
# https://github.com/hexojs/hexo-generator-category
category_generator:
  per_page: 10

# hexo-browsersync plugin
# https://github.com/hexojs/hexo-browsersync
browsersync:
  notify: false
  ui: false
  host: '127.0.0.1'
  port: 7782
  online: false
  ghostMode: false
  logSnippet: false
  open: false
  localOnly: true
  timestamps: false
  reloadDelay: 1000
  reloadThrottle: 1000
  reloadOnRestart: true

# hexo-renderer-marked plugin
# https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  # modifyAnchors: ''
  autolink: true

# hexo-server plugin
server:
  port: 7781
  log: true
  ip: 127.0.0.1
  compress: false
  serveStatic:
    cacheControl: true
    etag: false
    lastModified: false

# hexo-generator-tag
# https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 10

# hexo-toc
# add <!-- toc -->
# https://github.com/bubkoo/hexo-toc
toc:
  maxdepth: 2
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: before
    symbol: '#'
    style: anchor
